doctrine:
    dbal:
        connections:
            default:
                charset: utf8
                dbname: rkn-symfony
                default_table_options:
                    charset: utf8
                    collate: pl_PL.utf8
                driver: pdo_pgsql
                server_version: "5.7"
                url: "%env(resolve:DATABASE_URL)%"
            ew:
                charset: utf8
                dbname: ew3
                default_table_options:
                    charset: utf8
                    collate: pl_PL.utf8
                driver: pdo_pgsql
                server_version: "5.7"
                url: "%env(resolve:DATABASE_EW_URL)%"
        default_connection: default
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        default_entity_manager: default
        entity_managers:
            default:
                auto_mapping: true
                naming_strategy: doctrine.orm.naming_strategy.underscore
                connection: default
                mappings:
                    App:
                        alias: App
                        dir: "%kernel.project_dir%/src/Entity/App"
                        is_bundle: false
                        prefix: App\Entity
                        type: annotation
            ew:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                connection: ew
                mappings:
                    Ew:
                        alias: Ew
                        dir: "%kernel.project_dir%/src/Entity/Ew"
                        is_bundle: false
                        prefix: App\Entity
                        type: annotation
parameters:
    env(DATABASE_EW_URL): ""
    env(DATABASE_URL): ""

#parameters:
#    # Adds a fallback DATABASE_URL if the env var is not set.
#    # This allows you to run cache:warmup even if your
#    # environment variables are not available yet.
#    # You should not need to change this value.
#    env(DATABASE_URL): ''
#    env(DATABASE_EW_URL): ''
#
#doctrine:
#    dbal:
#        # configure these for your database server
#        default_connection: default
#        connections:
#            default:
#                dbname: rkn-symfony
#                driver: 'pdo_pgsql'
#                server_version: '5.7'
#                charset: utf8
#                default_table_options:
#                    charset: utf8
#                    collate: pl_PL.utf8
#                url: '%env(resolve:DATABASE_URL)%'
#            ew:
#                dbname: ew3
#                driver: 'pdo_pgsql'
#                server_version: '5.7'
#                charset: utf8
#                default_table_options:
#                    charset: utf8
#                    collate: pl_PL.utf8
#                url: '%env(resolve:DATABASE_EW_URL)%'
#    orm:
#        auto_generate_proxy_classes: '%kernel.debug%'
#        naming_strategy: doctrine.orm.naming_strategy.underscore
#        auto_mapping: true
#        default_entity_manager: default
#        entity_managers:
#            default:
#                connection: default
#                mappings:
#                    App:
#                        is_bundle: false
#                        type: annotation
#                        dir: '%kernel.project_dir%/src/Entity/App'
#                        prefix: 'App\Entity\App'
#                        alias: App
#            ew:
#                connection: ew
#                mappings:
#                    Ew:
#                        is_bundle: false
#                        type: annotation
#                        dir: '%kernel.project_dir%/src/Entity/Ew'
#                        prefix: 'App\Entity\Ew'
#                        alias: Ew
