<?php

namespace App\Controller;

use App\Entity\App\Pictures;
use App\Entity\Olimp;


use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use AppBundle\Form\FormValidationType;

use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;


class PicturesController extends Controller
{

    /**
     * @Route("/pictures/new", name="new_pictures")
     * Method({"GET", "POST"})
     */
    public function new(Request $request) {
        $pictures = new Pictures();
        $del=FALSE;
        $pictures->setDeleted($del);
        $pictures->setCreated(new \DateTime());
        $form = $this->createFormBuilder($pictures)
            ->add('title', TextType::class, array('label' => 'Tytuł','attr' => array('class' => 'form-control')))
            ->add('picture', FileType::class, array('label' => 'Wstaw obraz (png, jpeg)', 'attr' => array('class' => 'form-control-file')))
            ->add('creator', TextType::class, array('required' => false,'attr' => array('class' => 'form-control')))
            ->add('save', SubmitType::class, array(
                'label' => 'Utwórz',
                'attr' => array('class' => 'btn btn-primary mt-3')
            ))
            ->getForm();
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()) {
            $file = $pictures->getPicture();
            $PictureName = 'picture'.$this->generateUniqueFileName().'.'.$file->guessExtension();
            $file->move($this->getParameter('pictures_directory'), $PictureName);
            $pictures->setPicture($PictureName);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($pictures);
            $entityManager->flush();
            return $this->redirectToRoute('pictures_list');
        }
        return $this->render('pictures/new.html.twig', array(
            'form' => $form->createView()
        ));
    }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }


    /**
     * @Route("/pictures/list", name="pictures_list", methods="GET")
     */
    public function artciles() {
        $pictures= $this->getDoctrine()->getRepository(Pictures::class)
            ->findBy(
                array('deleted' => 'false'),
                array('created' => 'DESC')
            );


        $pgdb = new Olimp();
        $pgdb->dbConnect();

        $res = $pgdb->Q("SELECT o.uid AS id, o.org_id, o.name AS name, o.surname AS surname
													FROM mainframe.vroles_active_extend o
													
						WHERE o.org_id = 54223  ORDER BY  o.uid
          ");


        return $this->render('pictures/list.html.twig', array('pictures' => $pictures, 'members' => $res));
    }
}
